### Customer Login

POST http://127.0.0.1:8000/api/customer/login
Content-Type: application/json
Accept: application/json

{
    "email": "customer@test.com",
    "password": "password123"
}


### Customer Membership

GET http://127.0.0.1:8000/api/customer/membership
Accept: application/json
Authorization: Bearer 2|0vO92beoTgGfJD9KPa9vqdtmce1Ecl1zesFBqjUxaf941312

### Customer Membership

GET http://127.0.0.1:8000/api/customer/membership
Accept: application/json
Authorization: Bearer 3|ECbt83QIpYGItsDZT9SQkT6buXFE92MUoW8CjIUk72bd7274