### =========================================================
### CUSTOMER LOGIN
### =========================================================

POST http://127.0.0.1:8000/api/customer/login
Content-Type: application/json
Accept: application/json

{
    "email": "customer@test.com",
    "password": "password123"
}


### =========================================================
### CUSTOMER MEMBERSHIP
### Replace TOKEN-HERE with the newest token from login
### =========================================================

GET http://127.0.0.1:8000/api/customer/membership
Accept: application/json
Authorization: Bearer TOKEN-HERE


### =========================================================
### ACTIVATE NEW CUSTOMER
### No Authorization token required
### =========================================================

POST http://127.0.0.1:8000/api/customer/activate
Content-Type: application/json
Accept: application/json

{
    "membership_code": "MM-8OOUA8JN",
    "phone": "09123456789",
    "email": "customertwo@test.com",
    "password": "password",
    "password_confirmation": "password"
}

### Customer Login

POST http://127.0.0.1:8000/api/customer/login
Content-Type: application/json
Accept: application/json

{
    "email": "customertwo@test.com",
    "password": "password"
}

### Customer Transactions

GET http://127.0.0.1:8000/api/customer/transactions
Accept: application/json
Authorization: Bearer 12|Gijl27mySiQzxcABYBsoDDFqNVi7Vq7twaXmimbX1f1e02c8